import threading

JOB_PROGRESS = {}
ACTIVE_DOWNLOAD_TASKS = {}
ACTIVE_DOWNLOAD_CANCEL_EVENTS = {}
ACTIVE_DOWNLOAD_CANCEL_REASONS = {}
ACTIVE_DOWNLOAD_WORKER_FUTURES = {}
ACTIVE_DOWNLOAD_TASKS_LOCK = threading.Lock()
BACKGROUND_JOB_TASKS = set()
BACKGROUND_JOB_TASKS_LOCK = threading.Lock()

REDIS_CLIENT = None
REDIS_ERROR_LOCK = threading.Lock()
LAST_REDIS_ERROR_TS = 0.0

LAST_DOWNLOAD_TIME = {}
LAST_SETTINGS_CHANGE = {}
USER_SETTINGS_LOCK = threading.Lock()
LOCAL_USER_SETTINGS = {}
