import threading

JOB_PROGRESS = {}
ACTIVE_DOWNLOAD_TASKS = {}
ACTIVE_DOWNLOAD_CANCEL_EVENTS = {}
ACTIVE_DOWNLOAD_CANCEL_REASONS = {}
ACTIVE_DOWNLOAD_WORKER_FUTURES = {}
ACTIVE_DOWNLOAD_TASKS_LOCK = threading.Lock()
BACKGROUND_JOB_TASKS = set()
BACKGROUND_JOB_TASKS_LOCK = threading.Lock()

REDIS_CLIENT = None
REDIS_ERROR_LOCK = threading.Lock()
LAST_REDIS_ERROR_TS = 0.0

LAST_DOWNLOAD_TIME = {}
LAST_SETTINGS_CHANGE = {}
USER_SETTINGS_LOCK = threading.Lock()
LOCAL_USER_SETTINGS = {}

USER_PROFILE_LOCK = threading.Lock()
LOCAL_USER_PROFILES = {}
LOCAL_AUDIT_EVENTS = []
LOCAL_ROLE_INDEX = {"admin": set(), "superadmin": set()}

USAGE_LOCK = threading.Lock()
LOCAL_USAGE_COUNTERS = {}
LOCAL_JOB_COUNTED = {}
LOCAL_PAYMENT_DONE = {}
LOCAL_UPDATES_DONE = {}
LOCAL_PENDING_NONCES = {}
LOCAL_PAYMENT_USERS = {}
LOCAL_PAYMENT_PRODUCTS = {}
LOCAL_PAYMENT_ORDERS = {}
LOCAL_PAYMENT_RECORDS = {}
LOCAL_PAYMENT_REFUNDS = {}
LOCAL_PAYMENT_AUDIT = []
LOCAL_PAYMENT_SEQUENCES = {"users": 0, "products": 0, "orders": 0, "payments": 0, "refunds": 0, "audit": 0}
LOCAL_PAYMENT_ALERT_COUNTERS = {}
PAYMENTS_LOCK = threading.Lock()

METADATA_LOCK = threading.Lock()
LOCAL_METADATA_SESSIONS = {}
LOCAL_METADATA_INPUT = {}
LOCAL_METADATA_USER_ACTIVE = {}
